[build]
	publish = "dist"
	command = "npm run build"

[[redirects]]
	from = "/*"
	to = "index.html"
	status = 200

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"